<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class RolePermissionSeeder extends Seeder
{
    public const PERMISSIONS = [
        'manage users',
        'manage roles',
        'manage permissions',
        'manage shops',
        'manage products',
        'view products',
        'create products',
        'edit products',
        'delete products',
        'manage customers',
        'view customers',
        'create customers',
        'edit customers',
        'delete customers',
        'manage suppliers',
        'view suppliers',
        'create suppliers',
        'edit suppliers',
        'delete suppliers',
        'manage purchases',
        'view purchases',
        'create purchases',
        'edit purchases',
        'delete purchases',
        'manage purchase returns',
        'view purchase returns',
        'create purchase returns',
        'edit purchase returns',
        'delete purchase returns',
        'approve purchase returns',
        'manage stock',
        'view stock',
        'create stock',
        'edit stock',
        'delete stock',
        'distribute stock',
        'view stock distributions',
        'receive stock distributions',
        'manage sales',
        'manage sale returns',
        'manage expenses',
        'manage cash',
        'manage cheques',
        'manage dues',
        'manage cloth sewings',
        'view cloth sewings',
        'create cloth sewings',
        'edit cloth sewings',
        'delete cloth sewings',
        'manage received cloths',
        'view received cloths',
        'create received cloths',
        'edit received cloths',
        'delete received cloths',
        'manage carry men',
        'view carry men',
        'create carry men',
        'edit carry men',
        'delete carry men',
        'manage carry man work logs',
        'view carry man work logs',
        'create carry man work logs',
        'edit carry man work logs',
        'delete carry man work logs',
        'manage computer men',
        'view computer men',
        'create computer men',
        'edit computer men',
        'delete computer men',
        'manage computer man work logs',
        'view computer man work logs',
        'create computer man work logs',
        'edit computer man work logs',
        'delete computer man work logs',
        'manage garey men',
        'view garey men',
        'create garey men',
        'edit garey men',
        'delete garey men',
        'manage garey man work logs',
        'view garey man work logs',
        'create garey man work logs',
        'edit garey man work logs',
        'delete garey man work logs',
        'manage employees',
        'view employees',
        'create employees',
        'edit employees',
        'manage salaries',
        'view salaries',
        'create salaries',
        'manage salary advances',
        'view salary advances',
        'create salary advances',
        'edit salary advances',
        'delete salary advances',
        'view sales',
        'create sales',
        'edit sales',
        'delete sales',
        'view sale returns',
        'create sale returns',
        'edit sale returns',
        'delete sale returns',
        'approve sale returns',
        'view expenses',
        'create expenses',
        'edit expenses',
        'delete expenses',
        'view cash',
        'create cash',
        'edit cash',
        'delete cash',
        'view cheques',
        'create cheques',
        'edit cheques',
        'delete cheques',
        'view dues',
        'create dues',
        'edit dues',
        'delete dues',
        'view users',
        'create users',
        'edit users',
        'delete users',
        'view roles',
        'create roles',
        'edit roles',
        'delete roles',
        'view permissions',
        'create permissions',
        'edit permissions',
        'delete permissions',
        'view shops',
        'create shops',
        'edit shops',
        'delete shops',
    ];

    public function run(): void
    {
        app()[\Spatie\Permission\PermissionRegistrar::class]->forgetCachedPermissions();

        foreach (self::PERMISSIONS as $permission) {
            Permission::firstOrCreate(['name' => $permission, 'guard_name' => 'web']);
        }

        $superAdmin = Role::firstOrCreate(['name' => 'Super Admin', 'guard_name' => 'web']);
        $superAdmin->syncPermissions(self::PERMISSIONS);

        $shopExecutive = Role::firstOrCreate(['name' => 'Shop Executive', 'guard_name' => 'web']);
        $shopExecutive->syncPermissions([
            'manage customers',
            'manage sales',
            'manage sale returns',
        ]);
    }
}
